<?php
return array(
	'imei-service' => trans('all.service-imei'),
	'file-service' => trans('all.service-file'),
	'server-service' => trans('all.service-server'),
	'indexHome' => trans('all.home'),
	'sign-in' => trans('all.sign-in'),
	'sign-up' => trans('all.sign-up'),
	'add-fund-bank' => trans('all.add-fund-page.via-bank'),
	'area-client' => trans('all.client-area'),
	'orders-history' => trans('all.history-order'),
	'place-order-imei' => trans('all.place-order-imei'),
	'place-order-imei' => trans('all.place-order-imei'),
	'add-fund-paypal' => trans('all.add-fund-page.via-paypal'),
	'setting-profile' => trans('all.settings.personal-info'),
	'setting-change-pass' => trans('all.settings.change-pass'),
	'setting-change-question' => trans('all.settings.change-question'),
	'setting-email-notify' => trans('all.settings.email-notify'),
	'setting-security-login' => trans('all.settings.security-login'),
	'my-invoice' => trans('all.settings.invoice'),
	'my-statement' => trans('all.settings.statement'),
	'contact-us' => trans('all.contact'),
	'about-us' => trans('all.about-us'),
	'view-invoice' => trans('all.invoice-detail'),
	'index-blog' => trans('all.blog'),
	'error-404' => trans('all.error-404'),
);